# Site settings
title: Vocabulary UNECE
baseurl: "/vocabulary" # the subpath of your site, e.g. /blog

dataSet: "dataset:'22A'"
versions:
  bsp: v22A
  un-locodes: v2022-1
  vocab-codes: v1.0

markdown: kramdown
kramwdown:
  parse_block_html: true

collections:
  classes:
    output: true
    permalink: /:name
  properties:
    output: true
    permalink: /:name
  code-lists:
    output: true
    permalink: /:name
  unlocode-lists:
    output: true
    permalink: /:name
  vocab-codes:
    output: true
    permalink: /:name

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "classes"
    values:
      layout: "class"
      type: "class"
  -
    scope:
      path: ""
      type: "properties"
    values:
      layout: "property"
      type: "property"
  -
    scope:
      path: ""
      type: "code-lists"
    values:
      layout: "code-list"
      type: "code-list"
  -
    scope:
      path: ""
      type: "unlocode-lists"
    values:
      layout: "code-list"
      type: "unlocode-list"
  -
    scope:
      path: ""
      type: "vocab-codes"
    values:
      layout: "code-list"
      type: "vocab-code"

sass:
  sourcemap: development

exclude:
  - vendor
  - .idea
  - .git
  - .sass-cache
