# Site settings
title: Vocabulary UNTP
baseurl: "/vocabulary/untp" # the subpath of your site, e.g. /blog
dataSet: "dataset:'22A'"
versions:
  untp-core: 0.6.0-beta4
  untp-dpp: 0.6.0-beta4
  untp-dfr: 0.6.0-beta1
  untp-dcc: 0.6.0-beta1
  untp-dte: 0.6.0-beta1
  untp-dia: 0.6.0-beta1
markdown: kramdown
kramwdown:
  parse_block_html: true
collections:
  classes:
    output: true
    permalink: /:name
  properties:
    output: true
    permalink: /:name
  code-lists:
    output: true
    permalink: /:name
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "classes"
    values:
      layout: "class"
      type: "class"
  - scope:
      path: ""
      type: "properties"
    values:
      layout: "property"
      type: "property"
  - scope:
      path: ""
      type: "code-lists"
    values:
      layout: "code-list"
      type: "code-list"
sass:
  sourcemap: development
exclude:
  - vendor
  - .idea
  - .git
  - .sass-cache
