# Sample workflow for broken links check
name: Check deployment for broken links

on:
  # Manually run the deployment
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to check'
        required: true

jobs:
  # Build job
  linkinator:
    runs-on: ubuntu-latest
    steps:
    - name: "Run check for broken links"
      run: npx linkinator ${{ github.event.inputs.url }} --recurse
