name: jargon_onRelease

on:
  repository_dispatch:
    types: [ 'jargon_onRelease' ]

jobs:

  jargon_snapshot:
    uses: uncefact/.github/.github/workflows/jargon-release.yml@5ddd5d3830ddce466f27bfbbdc3723d2457313f5
    secrets: inherit
