name: jargon_onSnapshot

on:
  repository_dispatch:
    types: [ 'jargon_onSnapshot' ]

jobs:

  jargon_snapshot:
    uses: uncefact/.github/.github/workflows/jargon-snapshot.yml@main
    secrets: inherit
