# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to AWS S3
name: Deploy site preview to AWS S3

on:
  workflow_call:
    inputs:
      vocabulary_name:
        description: 'Vocabulary name'
        type: string
        required: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-1'


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: download-merged-vocabulary
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "uncefact/vocab-${{ github.event.client_payload.vocabulary_name }}"
        latest: true
        fileName: "merged.jsonld"
        out-file-path: ""
        tarBall: false
        zipBall: false
        extract: false
    - id: download-md-utility
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "uncefact/utilities"
        latest: true
        fileName: "vocab-md-generation-1.0.0.jar"
        tarBall: false
        zipBall: false
        extract: false
    - run: |
        rm -rf _classes
        rm -rf _properties
        rm -rf _code-lists
        mv _data/mapping.json .
        mv _data/*.csv .
        rm -rf _data
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - run: java -jar vocab-md-generation-1.0.0.jar
    - run: |
        mv mapping.json _data/
        mv *.csv _data/
    - run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add _data
        git add _classes
        git add _properties
        git add _data
        git commit -m "release: ${{ github.event.client_payload.vocabulary_name }} - ${{ github.event.client_payload.release.version }}"
        git push

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.6.5" # Not needed with a .ruby-version file
    - name: "Bundle install"
      run: bundle install
    - name: "Build Site"
      run: bundle exec jekyll build --config _config_preview.yml
    - name: "Deploy to AWS S3"
      run: aws s3 sync ./_site/ s3://uncefact-vocab-preview-sam-bucket-private/jargon --delete --cache-control max-age=604800
    
