# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Jekyll site to AWS S3
name: Deploy site preview to AWS S3 (untp-pages) - release tag

on:
  workflow_dispatch:
  push:
    tags:
      - 'untp**'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-west-1'


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.6.5" # Not needed with a .ruby-version file
    - name: "Bundle install"
      run: bundle install
    - name: "Build Site"
      run: bundle exec jekyll build --config _config_preview.yml
    - name: "Deploy to AWS S3"
      run: |
        aws s3 sync ./_site/ s3://uncefact-vocab-preview-sam-bucket-private/vocabulary/${{ github.ref_name }} --delete --cache-control max-age=604800
        aws cloudfront create-invalidation --distribution-id "E32QP2QS6SXRHC" --paths "/vocabulary/${{ github.ref_name }}/*"