# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Workflow to update UN/LOCODEs vocabulary from uncefact/codes-locode repo
name: Update UN/LOCODEs vocabulary files

on:
  # Runs on pull requests against main branch
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "uncefact/codes-locode"
        latest: true
        fileName: "*.jsonld"
        tarBall: false
        zipBall: false
        extract: false

    - name: snapshot PR
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "chore: update UN/LOCODEs vocabulary"
        delete-branch: true
        title: 'chore: update UN/LOCODEs vocabulary'
        body: |
          Updates UN/LOCODEs JSON-LD vocabulary published as an artifact as a part of unece/codes-locode release
        base: 'main'
        branch: create-pull-request/unlocode-vocabularies
        draft: true

